import type { Metadata } from "next";
import "@/public/globals.css";

import {Fredoka, Poppins} from "next/font/google";

const fredoka = Fredoka({
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700"],
    variable: "--font-fredoka",
    display: "swap",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-poppins",
})



export const metadata: Metadata = {
  title: "RePomodoro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fredoka.variable} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
